services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PassW0rd}
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce_db}
    env_file:
      - ./services/users/.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s
    

  mongo:
    image: mongo:8.0
    volumes:
      - mongodata:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  users-service:

    build: 
      context: .
      dockerfile: infra/dockerfiles/Dockerfile.users
    image: ecommerce/users-service:latest
    container_name: users-service
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://admin:PassW0rd@postgres:5432/ecommerce_users}
      - DB_HOST=postgres
    env_file:
      - ./services/users/.env.prod
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s
  
  products-service:
    build: 
      context: .
      dockerfile: infra/dockerfiles/Dockerfile.products
    container_name: products-service
    image: ecommerce/products-service:latest
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://admin:PassW0rd@postgres:5432/ecommerce_products}
      - DB_HOST=postgres
    env_file:
      - ./services/products/.env.prod
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8002:8002"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  cart-service:
    build: 
      context: .
      dockerfile: infra/dockerfiles/Dockerfile.cart
    container_name: cart-service
    image: ecommerce/cart-service:latest
    env_file:
      - ./services/cart/.env.prod
    environment:
      - MONGO_URI=${MONGO_DB_URI:-mongodb://mongo:27017/ecommerce_cart}
      - USERS_SERVICE_URL=http://users-service:8001
      - PRODUCTS_SERVICE_URL=http://products-service:8002
    depends_on:
      mongo:
        condition: service_healthy
      users-service:
        condition: service_healthy
      products-service:
        condition: service_healthy
    ports:
      - "8003:8003"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8003/health || exit 1"]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 40s

  orders-service:
    build: 
      context: .
      dockerfile: infra/dockerfiles/Dockerfile.orders
    container_name: orders-service
    image: ecommerce/orders-service:latest
    env_file:
      - ./services/orders/.env.prod
    environment:
      - MONGO_URI=${MONGO_DB_URI:-mongodb://mongo:27017/ecommerce_orders}
      - USERS_SERVICE_URL=http://users-service:8001
      - PRODUCTS_SERVICE_URL=http://products-service:8002
      - CART_SERVICE_URL=http://cart-service:8003
    depends_on:
      mongo:
        condition: service_healthy
      users-service:
        condition: service_healthy
      products-service:
        condition: service_healthy
      cart-service:
        condition: service_healthy
    ports:
      - "8004:8004"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8004/health || exit 1"]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 40s

volumes:
  pgdata:
  mongodata:

networks:
  backend:
    driver: bridge