services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PassW0rd}
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce_db}
    env_file:
        - ./fast_api/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-ecommerce_db} || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
    

  mongo:
    image: mongo:8.0
    volumes:
      - mongodata:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  fast_api:
    build: 
      context: ./fast_api
      dockerfile: ../dockerfiles/Dockerfile.fastapi
    environment:
      # FIX: Change 'localhost' to the service name 'postgres'
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://admin:P%40ssW0rd@postgres:5432/ecommerce_db}
      # You can also use a generic host variable
      - DB_HOST=postgres
    env_file:
      - ./fast_api/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  express_api:
    build: 
      context: ./express_api
      dockerfile: ../dockerfiles/Dockerfile.express
    env_file:
      - ./express_api/.env
    environment:
      - MONGO_URI=${MONGO_DB_URI:-mongodb://127.0.0.1:27017/ecommerce_db}
    depends_on:
      # FIX 2: Use the 'service_healthy' condition for both dependencies
      mongo:
        condition: service_healthy
      fast_api:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      retries: 10
      timeout: 5s

volumes:
  pgdata:
  mongodata:

networks:
  backend:
