services:

  # Gateway Service
  gateway:
    build: ../gateway
    ports:
      - "8000:8000"
    depends_on:
      - products
      - cart
      - orders
      - postgres
    networks:
      - ecommerce_network

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
    env_file:
      - ../.env
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  # Redis for caching/sessions
  redis:
    image: redis:7-alpine
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    


  # Products Service
  products:
    build:
      context: ../dockerfiles
      dockerfile: Dockerfile.products
    volumes:
      - ../products:/app/products
    env_file:
      - ../.env
    environment:
      - DATABASE_URL={DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - SERVICE_NAME=products
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce_network
    expose:
      - "8001"

  cart:
    build: 
      context: ../dockerfiles
      dockerfile: Dockerfile.cart
    volumes:
      - ../cart:/app/cart
    env_file:
      - ../.env
    environment:
      - DATABASE_URL={DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - SERVICE_NAME=cart
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce_network
    expose:
      - "8002"

  orders:
    build: 
      context: ../dockerfiles
      dockerfile: Dockerfile.orders
    volumes:
      - ../orders:/app/orders
    env_file:
      - ../.env 
    environment:
      - DATABASE_URL={DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - SERVICE_NAME=orders
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce_network
    expose:
      - "8003"
    

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  ecommerce_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

    