
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: ecommerce
data:
  MONGO_URI: "mongodb://mongo:27017/ecommerce_cart"
  USERS_SERVICE_URL: "http://users:8001"
  PRODUCTS_SERVICE_URL: "http://products:8002"
  PORT: "8003"