apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: ecommerce
data:
  MONGO_URI: "mongodb://mongo-service:27017/ecommerce_orders"
  USERS_SERVICE_URL: "http://users-service:8001"
  PRODUCTS_SERVICE_URL: "http://products-service:8002"
  CART_SERVICE_URL: "http://cart-service:8003"
  PORT: "8004"