
apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
  namespace: ecommerce
data:
  DATABASE_URL: "postgresql+asyncpg://admin:PassW0rd@postgres:5432/ecommerce_products"
  DB_HOST: "postgres"
  PROJECT_NAME: "Products Service"
  PROJECT_VERSION: "1.0.0"