apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: ecommerce
data:
  DATABASE_URL: "postgresql+asyncpg://admin:PassW0rd@postgres:5432/ecommerce_users"
  DB_HOST: "postgres"
  PROJECT_NAME: "Users Service"
  PROJECT_VERSION: "1.0.0"