apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: ecommerce
  labels:
    app: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo-service
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP