apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: ecommerce
  labels:
    app: cart
spec:
  type: NodePort
  selector:
    app: cart
  ports:
  - port: 8003
    targetPort: 8003
    nodePort: 30003
    protocol: TCP