apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: ecommerce
  labels:
    app: orders-service
spec:
  type: NodePort
  selector:
    app: orders-service
  ports:
  - port: 8004
    targetPort: 8004
    nodePort: 30004
    protocol: TCP