apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: ecommerce
  labels:
    app: orders
spec:
  type: NodePort
  selector:
    app: orders
  ports:
  - port: 8004
    targetPort: 8004
    nodePort: 30004
    protocol: TCP