apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: ecommerce
  labels:
    app: users-service
spec:
  type: NodePort
  selector:
    app: users-service
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30001
    protocol: TCP