name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      # Node setup
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and test Node services
        run: |
          cd services/cart && npm install && npm test
          cd ../orders && npm install && npm test

      # Python setup
      - uses: actions/setup-python@v4
        with: { python-version: "3.13" }

      - name: Install and test Python services
        run: |
          cd services/products && pip install -r requirements.txt && pytest
          cd ../users && pip install -r requirements.txt && pytest
